version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php-fpm
      - db
    networks:
      - dev-env

  php-fpm:
    image: php:8-fpm
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/html
      - ./logs/php:/var/log/php
    depends_on:
      - db
    networks:
      - dev-env

  db:
    image: mariadb
    restart: always
    volumes:
      - ./bbdd:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    networks:
      - dev-env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
    networks:
      - dev-env

networks:
  dev-env: {}